[workspace]
members = ["crates/*"]
exclude = ["crates/floem"]
resolver = "2"

[workspace.dependencies]
# floem = {path = "crates/floem"}
nix-installed-list = {path = "crates/nix-installed-list"}
nix-channel-list = {path = "crates/nix-channel-list"}
